name: flair_pseudo_api
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cpuonly=1.0=0
  - freetype=2.9.1=h8a8886c_1
  - gunicorn=20.0.4=py37_0
  - intel-openmp=2020.0=166
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h7b6447c_0
  - pillow=7.1.2=py37hb39fc2d_0
  - pip=20.0.2=py37_1
  - python=3.7.7=hcf32534_0_cpython
  - pytorch=1.4.0=py3.7_cpu_0
  - readline=8.0=h7b6447c_0
  - setuptools=46.1.3=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - torchvision=0.5.0=py37_cpu
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - attrs==19.3.0
    - boto==2.49.0
    - boto3==1.13.2
    - botocore==1.16.2
    - bpemb==0.3.0
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.4.1
    - cycler==0.10.0
    - dbx-stopwatch==1.6
    - decorator==4.4.2
    - deprecated==1.2.9
    - docutils==0.15.2
    - filelock==3.0.12
    - flair==0.4.5
    - flask==1.1.2
    - future==0.18.2
    - gensim==3.8.3
    - hyperopt==0.2.4
    - idna==2.9
    - importlib-metadata==1.6.0
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - jmespath==0.9.5
    - joblib==0.14.1
    - kiwisolver==1.2.0
    - langdetect==1.0.8
    - markupsafe==1.1.1
    - matplotlib==3.2.1
    - more-itertools==8.2.0
    - mpld3==0.3
    - networkx==2.4
    - packaging==20.3
    - pluggy==0.13.1
    - py==1.8.1
    - pyparsing==2.4.7
    - pytest==5.4.1
    - python-dateutil==2.8.1
    - regex==2020.4.4
    - requests==2.23.0
    - s3transfer==0.3.3
    - sacremoses==0.0.43
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - segtok==1.5.9
    - sentencepiece==0.1.86
    - smart-open==2.0.0
    - sqlitedict==1.6.0
    - tabulate==0.8.7
    - tokenizers==0.5.2
    - tqdm==4.46.0
    - transformers==2.8.0
    - urllib3==1.24.3
    - wcwidth==0.1.9
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.1.0

